<?php declare(strict_types=1);

namespace MoorlFormsExample;

use Doctrine\DBAL\Connection;
use MoorlFoundation\Core\Service\DataService;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\ActivateContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;
use Shopware\Core\Framework\Plugin\Context\UpdateContext;

class MoorlFormsExample extends Plugin
{
    public const NAME = 'MoorlFormsExample';
    public const DATA_CREATED_AT = '1999-03-03 03:02:22.000';
    public const PLUGIN_TABLES = [];
    public const SHOPWARE_TABLES = [];
    public const INHERITANCES = [];

    public function activate(ActivateContext $activateContext): void
    {
        parent::activate($activateContext); // TODO: Change the autogenerated stub

        try {
            /* @var $dataService DataService */
            $dataService = $this->container->get(DataService::class);
            $dataService->install(self::NAME);
        } catch (\Exception $exception) {
        }
    }

    public function update(UpdateContext $updateContext): void
    {
        parent::update($updateContext); // TODO: Change the autogenerated stub

        try {
            /* @var $dataService DataService */
            $dataService = $this->container->get(DataService::class);
            $dataService->install(self::NAME);
        } catch (\Exception $exception) {
        }
    }

    public function uninstall(UninstallContext $context): void
    {
        parent::uninstall($context);

        if ($context->keepUserData()) {
            return;
        }
    }
}
